apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: webapp
      image: 787685023644.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password"
        - name: DBPORT
          value: "3306"
